# netlify.toml

[build]
  # This is the command Netlify will run to build your site.
  command = "pnpm build"

  # This is the directory that contains the built site.
  publish = "apps/web/dist"

[build.environment]
  # Specify the Node.js version to use.
  NODE_VERSION = "20"

  # Specify the pnpm version to use.
  PNPM_VERSION = "10"

  # Increase memory for large builds
  NODE_OPTIONS = "--max_old_space_size=4096"

# Prerendering for SEO - Serves pre-rendered HTML to search engine bots
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "reports/lighthouse.html"

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Existing COOP/COEP headers for SharedArrayBuffer support
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "same-site"
