#!/bin/bash

set -euxo pipefail

DOCKER_VERSION_STRING="5:28.1.1-1~debian.12~bookworm"
apt-get install -y docker-ce=${DOCKER_VERSION_STRING} docker-ce-cli=${DOCKER_VERSION_STRING} containerd.io docker-buildx-plugin docker-compose-plugin

sed -i 's/ulimit -Hn/# ulimit -Hn/g' /etc/init.d/docker
